apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: istio-system
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: istio
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'


---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: istio-base
    spec:
      destination:
        namespace: istio-system
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - kind: ServiceAccount
        jsonPointers:
        - /imagePullSecrets
        - /secrets
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
          - /webhooks/0/failurePolicy
      project: istio-system
      source:
        helm:
          valueFiles:
          - values-base.yaml
        path: .
        repoURL: https://github.com/mgcalvo-istio-demo/istio-base-argocd-helm.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Replace=false
        - PruneLast=true
        - CreateNamespace=true
