apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kiali-operator
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: kiali-operator
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'


---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kiali-operator
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: kiali-operator
    spec:
      destination:
        namespace: kiali-operator
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - kind: ServiceAccount
        jsonPointers:
        - /imagePullSecrets
        - /secrets
      project: kiali-operator
      source:
        helm:
          valueFiles:
          - values.yaml
        path: .
        repoURL: https://github.com/mgcalvo-istio-demo/istio-kiali-operator-argocd-helm.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Replace=false
        - PruneLast=true
        - CreateNamespace=true
