apiVersion: v2
name: istio-base
description: A Helm chart for Kubernetes
type: application
version: 1.18.0
appVersion: "1.18.0"
dependencies:
  - name: base
    version: 1.18.0
    repository: "https://istio-release.storage.googleapis.com/charts"
